# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Chat-ApppChellenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chat-ApppChellenge
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'  
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

end
